### ISSUE TITLE
Cannot install using pip from pypi

### ISSUE THREAD

**Issue by kirantambe** [raff/elseql#2]
if i do a 
`pip install elseql`
i get
`Collecting elseql
  Using cached elseql-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9y/9ftkyk654s37_1k7_gthl1s80000gn/T/pip-build-kG2Tq1/elseql/setup.py", line 21, in <module>
        long_description=open("README.md").read(),
    IOError: [Errno 2] No such file or directory: 'README.md'`
Cloning and installing using setup.py works
`pip install git+https://github.com/raff/elseql.git` also works

**Comment by briansorahan** [comment]
I'm also seeing this error.
Trying to build a docker image with this:

```
FROM python:2.7.14-alpine
RUN  pip install elseql
```

**Comment by raff** [comment]
Can you update ? You should now get 0.3.0. I have also fixed a few things broken with ElasticSearch >= 5.x.

**Comment by raff** [comment]
The docker image now also works (but I had to add a couple of dependencies):

```
 FROM python:2.7.14-alpine
 RUN apk add --update python-dev py-pip gcc libc-dev linux-headers && rm -rf /var/cache/apk/*
 RUN  pip install elseql
```

**Comment by briansorahan** [comment]
@raff That worked! I just pushed [this](https://hub.docker.com/r/bsorahan/elseql/).
Thank you.
